project:
  type: website
  output-dir: docs

resources:
  - files/**
  - google8b760d6b56e7c3b4.html

website:
  title: "Yusuke Okano"
  site-url: "https://yusuke-okano.github.io/"
  description: "Yusuke Okano is a Ph.D. student in Economics at Hitotsubashi University. His research lies at the intersection of health economics and environmental economics, with interests in climate adaptation, energy, housing, and applied microeconomics."

  open-graph: true
  search: false

  navbar:
    background: light
    foreground: dark

    left:
      - href: research.qmd
        text: Research
        
      - href: presentations.qmd
        text: Presentations

      - href: files/CV_Yusuke_Okano.pdf
        text: CV

    right:
      - href: index-ja.qmd
        text: 日本語ページ

      # - icon: github
      #   href: https://github.com/Yusuke-OKANO

      - icon: envelope
        href: "mailto:yokano.amecon@gmail.com"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false