project:
  type: website
  output-dir: docs
  
resources:
    - files/CV_Yusuke_Okano.pdf
    - google8b760d6b56e7c3b4.html

website:
  title: "Yusuke Okano"
  site-url: "https://yusuke-okano.github.io/"
  description: "Yusuke Okano is a PhD student in Economics at Hitotsubashi University. His research interests include health economics, environmental economics, and applied microeconometrics."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: presentations.qmd
        text: Presentations
      - href: cv.qmd
        text: CV
    right:
      - href: index-ja.qmd
        text: 日本語
      # - icon: github
      #   href: https://github.com/Yusuke-OKANO

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false